# Generated by Django 3.1.3 on 2020-11-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField(blank=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=1)),
                ('index', models.IntegerField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('file', models.ImageField(default='images/test/no_image.png', upload_to='')),
                ('file_small', models.ImageField(default='images/test/no_image.png', upload_to='')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.gallery')),
            ],
        ),
    ]
