# Generated by Django 3.1.3 on 2020-11-04 22:29

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20201104_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=galleries.models.image_upload_path),
        ),
    ]
