# Generated by Django 3.1.3 on 2020-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20201104_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
    ]
