# Generated by Django 3.1.3 on 2020-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20201104_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='visible',
            field=models.BooleanField(default=1),
        ),
    ]
