# Generated by Django 3.1.3 on 2020-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_auto_20201104_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
