# Generated by Django 3.1.3 on 2020-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_auto_20201105_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(upload_to=''),
        ),
    ]
