# Generated by Django 3.1.3 on 2020-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_auto_20201105_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
    ]
