# Generated by Django 3.1.3 on 2020-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
