# Generated by Django 3.1.3 on 2020-11-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0013_auto_20201106_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
