# Generated by Django 3.1.3 on 2020-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0014_auto_20201107_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
