# Generated by Django 3.1.3 on 2020-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0017_remove_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
