# Generated by Django 3.1.3 on 2020-11-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='photo',
            new_name='image',
        ),
    ]
