# Generated by Django 3.1.3 on 2020-11-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name_plural': 'Bio'},
        ),
        migrations.AddField(
            model_name='social',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='social',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
